[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F429ZI"
rustflags = [
    "-C", "linker=arm-none-eabi-gcc",
    "-C", "link-arg=-Wl,--gc-sections",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-specs=nano.specs",
    "-C", "link-arg=-lc",
    "-C", "link-arg=-lm",
]

[build]
target = "thumbv7em-none-eabihf"
